name: Build

on:
  push:
    branches: [ nextgen ]
  pull_request:
    branches: [ nextgen ]
  issues:
    types: [opened, edited, milestoned]
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '16'
      - name: Grant all permissions for theme
        run: sudo chmod -R 777 theme
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: jdk16
          arguments: genSources build
          gradle-version: wrapper
      - name: Copy artifact
        run: |
          cd build/libs
          export LB_VERSION=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          cp $LB_VERSION liquidbounce.jar
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: liquidbounce.jar
          path: build/libs/liquidbounce.jar
          



